### model
model_name_or_path: /flash2/aml/public/models/Llama-3.1-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: /flash2/aml/zjliu24/gpqa_agent/post_train/ds_config.json

### dataset
dataset: gpqa_qwq_inf_cft
template: llama3
cutoff_len: 20480
max_samples: 20000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /flash2/aml/zjliu24/gpqa_agent/post_train/training_inst_cft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 2.0e-6
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
